// Tour steps — generated by in-app editor; safe to hand-edit.

export const tourSteps = [
  {
    id: "welcome",
    title: "What is a tuning lattice?",
    body: "A tuning lattice is a diagram used to design a scale. It's an arrangement of notes where each axis represents an interval. \n\nHere, horizontal connections are perfect fifths (the 3rd harmonic), and vertical connections are pure major thirds (the 5th harmonic).\n",
    anchor: { corner: "top-left", dx: 216, dy: 91 },
  },
  {
    id: "step-mnqrrav5",
    title: "Add notes and listen",
    body: "SHIFT-CLICK to create some nodes that connect to our fundamental C. See how they move left/right by fifths and up/down by thirds.\n\nClick a note to hear it, and click again to turn it off. \n",
    anchor: { corner: "top-left", dx: 215, dy: 96 },
  },
  {
    id: "step-mnqs4cvl",
    title: "Make it pulse",
    body: "Now start one pulsing: hold down the L key, click on a node, and hold the mouse down for some amount of time — the longer you hold, the longer the cycle will be.\n\nClick again to turn it fully on, and again to turn it off.\n",
    anchor: { corner: "top-left", dx: 210, dy: 94 },
  },
  {
    id: "step-mnqs6o8q",
    title: "Play it like an instrument",
    body: "You can play your scale with your computer keyboard. From the menu below: \n\nTry \"Piano Keyboard\" to turn your letters into a two-octave piano layout (where C is mapped to Z and Y, C# is S and 7, etc). \n\nOr try Isomorphic to map the shape you see directly to your keyboard (see the letters that appear over each note). You can also play with a MIDI controller.\n",
    anchor: { corner: "bottom-left", dx: 16, dy: -84 },
    arrow: { x: 10.8, y: 84.1 },
  },
  {
    id: "step-mnqsctlp",
    title: "Start a sequence",
    body: "You can animate your scale. From the panel below, open the Play menu, choose a Sequence and a Rhythm, press Build and then Play.\n\nTry adding/removing notes while it plays.\n",
    anchor: { corner: "bottom-right", dx: -284, dy: -84 },
  },
  {
    id: "step-mnqsctlp-copy-mnrp4546",
    title: "Make it stop!",
    body: "Press SPACEBAR to stop and start the Pattern, or SHIFT-SPACEBAR to stop all notes.\n",
    anchor: { corner: "bottom-right", dx: -284, dy: -84 },
  },
  {
    id: "step-mnqsvr1k",
    title: "Composing with Snapshots",
    body: "Play around - find some notes and a patterns or drones you like.\n\nWhen you have something, press OPTION-1 to save it as a Snapshot. Now all you need to do to return to it is to press the number 1.\n\nMake a few more snapshots with OPTION-2, OPTION-3, etc. Use Snapshot Options below to change what gets recalled, and Export your composition to save it for later.",
    anchor: { corner: "bottom-left", dx: 360, dy: -79 },
  },
  {
    id: "step-mnqt9z1w",
    title: "Let's go 3D!",
    body: "Hold the letter Z and click a note to add notes that relate by a new interval: the 7th harmonic.\n\nClick and drag to rotate your view. Press ESCAPE to leave Z-edit mode.\n",
    anchor: { corner: "top-left", dx: 209, dy: 95 },
  },
  {
    id: "step-mnqu2tyu",
    title: "Page Layout Tool",
    body: "Switch to Print view to enter the page layout tool. Adjust your view and click Freeze in the message above to lock your position. You can edit everything - positions, titles, fonts, custom text, and export image files.",
    anchor: { corner: "top-left", dx: 212, dy: 115 },
  },
  {
    id: "step-mnqu4z3g",
    title: "Saving Your Lattice",
    body: "Your lattice is saved in a unique URL, so you can bookmark it or share it easily. You can also save it as a file to your computer (File > Save Lattice)",
    anchor: { corner: "top-left", dx: 355, dy: 81 },
  },
  {
    id: "step-mnqu83k1",
    title: "Presets",
    body: "Explore Presets to explore more tunings. (Careful - it will replace your work, so be sure to save it if you want to return to it.)",
    anchor: { corner: "top-right", dx: -377, dy: 84 },
  },
  {
    id: "step-mnqucafx",
    title: "The Tuner",
    body: "Practice with the Tuner to improve your intonation within your scale.",
    anchor: { corner: "top-right", dx: -18, dy: 78 },
  },
  {
    id: "learn-more",
    title: "Learn & Get Help",
    body: "Click \"Learn & Get Help\" any time\nto find the user's guide and replay this tour.",
    anchor: { corner: "top-right", dx: -12, dy: 115 },
  },
  {
    id: "done",
    title: "You're set",
    body: "Have fun exploring just intonation.",
    anchor: { corner: "top-right", dx: -490, dy: 337 },
    isFinal: true,
  },
];
